version: '3'
services:
  inspect-me:
    build: ./inspect-me
    ports:
      - 127.0.0.1:8001:80

  agent-keith:
    build: ./agent-keith
    ports:
      - 127.0.0.1:8002:80

  md5-minus-minus:
    build: ./md5--
    ports:
      - 127.0.0.1:8003:80

  keith-logger:
    build: ./keith-logger
    ports:
      - 127.0.0.1:8004:80

  s-q-l:
    build: ./s-q-l/app
    ports:
      - 127.0.0.1:8005:80
  
  s-q-l-mysql:
    build: ./s-q-l/mysql
    ports:
      - 127.0.0.1:3306:3306
      
  networked-password:
    build: ./networked-password
    ports:
      - 127.0.0.1:8006:80
