version: '3'
services:
  inspect-me:
    build: ./inspect-me
    ports:
      - 127.0.0.1:8001:80

  agent-keith:
    build: ./agent-keith
    ports:
      - 127.0.0.1:8002:80

  md5-minus-minus:
    build: ./md5--
    ports:
      - 127.0.0.1:8003:80

  keith-logger:
    build: ./keith-logger
    ports:
      - 127.0.0.1:8004:80

  ess-que-el:
    build: ./ess-que-el/app
    ports:
      - 127.0.0.1:8005:80
  
  ess-que-el-mysql:
    build: ./ess-que-el/mysql
    ports:
      - 127.0.0.1:3306:3306